###### 변수 Variables
### Base URL
@BASE_URL = http://localhost:20102
### Product ID
@productId = 6
#################################################

### Get inventory by productId
GET {{BASE_URL}}/api/v1/inventories/{{productId}}


### Increase inventory stock quantity
PATCH {{BASE_URL}}/api/v1/inventories/{{productId}}/quantity
Content-Type: application/json

{
  "quantity": 10
}
