###### Variables
### Base URL
@BASE_URL = http://localhost:20104
#################################################

### Initialize payment
POST {{BASE_URL}}/api/v1/payments
Content-Type: application/json

{
  "orderId": "{{orderId}}",
  "customerId": 1,
  "amount": 398000,
  "currency": "KRW",
  "idempotencyKey": "{{$uuid}}",
  "items": [
    {
      "productId": {{productId}},
      "unitPrice": 199000,
      "quantity": 2,
      "lineAmount": 398000,
      "currency": "KRW"
    }
  ]
}
